# LinearRegression from Scratch


# 구현할 것
- 공부시간과 성적간의 관계를 모델링한다.
    - **머신러닝 모델(모형)이란** 수집한 데이터를 기반으로 입력값(Feature)와 출력값(Target)간의 관계를 하나의 공식으로 정의한 함수이다. 그 공식을 찾는 과정을 **모델링**이라고 한다.
    - 이 예제에서는 공부한 시험시간으로 점수를 예측하는 모델을 정의한다.
    - 입력값과 출력값 간의 관계를 정의할 수있는 다양한 함수(공식)이 있다. 여기에서는 <font color='red'>딥러닝과 관계가 있는 **Linear Regression** 을 사용해본다.</font>
    - feature에 가중치를 곱하여 예측한다. (feature 하나에 가중치 하나)

# 데이터 확인
- 입력데이터: 공부시간
- 출력데이터: 성적

|공부시간|점수|
|-|-|
|1|20|
|2|40|
|3|60|

우리가 수집한 공부시간과 점수 데이터를 바탕으로 둘 간의 관계를 식으로 정의 할 수 있으면 **내가 몇시간 공부하면 점수를 얼마 받을 수 있는지 예측할 수 있게 된다.**   
수집한 데이터를 기반으로 앞으로 예측할 수있는 모형을 만드는 것이 머신러닝 모델링이다.

  

## 학습(훈련) 데이터셋 만들기
- 모델을 학습시키기 위한 데이터셋을 구성한다.
- 입력데이터와 출력데이터을 각각 다른 행렬로 구성한다.
- 하나의 데이터 포인트의 입력/출력 값은 같은 index에 정의한다.

### 선형회귀 (Linear Regression)
- Feature들의 가중합을 이용해 Target을 추정한다.
- Feature에 곱해지는 가중치(weight)들은 각 Feature가 Target 얼마나 영향을 주는지 영향도가 된다.
    - 음수일 경우는 target값을 줄이고 양수일 경우는 target값을 늘린다.
    - 가중치가 0에 가까울 수록 target에 영향을 주지 않는 feature이고 0에서 멀수록 target에 많은 영향을 준다.
- 모델 학습과정에서 가장 적절한 Feature의 가중치를 찾아야 한다.
      

\begin{align}
&\large \hat{y} = W\cdot X + b\\
&\small \hat{y}: \text{모델추정값}\\
&\small W: \text{가중치}\\
&\small X: \text{Feature(입력값)}\\
&\small b: \text{bias(편향)}
\end{align}



## Train dataset 구성
- Train data는 feature(input)와 target(output) 각각 2개의 행렬로 구성한다.
- Feature의 행은 관측치(개별 데이터)를 열을 Feature(특성, 변수)를 표현한다. 이 문제에서는 `공부시간` 1개의 변수를 가진다.
- Target은 모델이 예측할 대상으로 행은 개별 관측치, 열은 각 항목에 대한 정답으로 구성한다.   
  이 문제에서 예측할 항목은 `시험점수` 한개이다.

In [14]:
import torch

X_train = torch.tensor([[1.0], [2.0], [3.0]])
y_train = torch.tensor([[20.], [40.], [60.]])
X_train.size() , y_train.shape

(torch.Size([3, 1]), torch.Size([3, 1]))

## 파라미터 (weight, bias) 정의
- 학습대상/최적화 대상

In [ ]:
# weight: 형태 - feature가 1개 (1. 출력값의 개수 -1)
weight = torch.randn(1,1, requires_grad=True) # [1: feature수, 1:예측 정답개수] , 최적화 할 값에 requires_grad=True 를 한다.
bias = torch.randn(1, requires_grad=True) # 1: 정답 개수
print(weight.size(), bias.size())


torch.Size([1, 1]) torch.Size([1])


In [7]:
weight

tensor([[0.7509]], requires_grad=True)

In [8]:
bias

tensor([0.6815], requires_grad=True)

In [18]:
### 추론
pred = X_train @ weight + bias
print("추론한 시험점수:", pred)

추론한 시험점수: tensor([[0.0280],
        [0.3388],
        [0.6496]], grad_fn=<AddBackward0>)


In [19]:
pred.grad_fn

In [22]:
### 오차계산 (MSE)
loss = torch.mean((pred - y_train)**2, dim=0)
loss

tensor([1831.4525], grad_fn=<MeanBackward1>)

In [23]:
(pred - y_train)**2

tensor([[ 398.8813],
        [1573.0100],
        [3522.4663]], grad_fn=<PowBackward0>)

In [24]:
#### weight와 bais를 업데이트
## 1. gradient를 계산 (loss / weight, loss / bias)
loss.backward()

In [25]:
weight.grad, bias.grad

(tensor([[-184.8970]]), tensor([-79.3224]))

In [26]:
#### 2. weight, bias를 업데이트
###  현재값 - 학습률 * grad
lr = 0.1
weight.data = weight.data - lr * weight.grad
bias.data = bias.data - lr * bias.grad

print("새 weight, bias")
print(weight.data, bias.data)

새 weight, bias
tensor([[18.8005]]) tensor([7.6494])


In [28]:
# 다시 추론
pred2 = X_train @ weight + bias
print(pred2)

tensor([[26.4499],
        [45.2504],
        [64.0510]], grad_fn=<AddBackward0>)


In [30]:
pred

tensor([[0.0280],
        [0.3388],
        [0.6496]], grad_fn=<AddBackward0>)

In [29]:
# 새로업데이트 오차
torch.mean((pred2-y_train)**2)

tensor(28.5264, grad_fn=<MeanBackward0>)

### 모델링

In [ ]:
# 모델 정의 ( 함수 또는 클래스로 정의 )
weight = torch.randn(1,1,requires_grad=True)
bias = torch.randn(1, requires_grad=True)

def linear_model(X):
    return X @ weight + bias    # 출력할 값의 개수

In [33]:
# 오차계산 함수 (MSE)
def mse_loss(pred,y):
    return torch.mean((pred-y)**2)

### 학습
1. 모델을 이용해 추정한다.
   - pred = model(input)
1. loss를 계산한다.
   - loss = loss_fn(pred, target)
1. 계산된 loss를 파라미터에 대해 미분하여 계산한 gradient 값을 각 파라미터에 저장한다.
   - loss.backward()
1. optimizer를 이용해 파라미터를 update한다.
   - optimizer.step()  
1. 파라미터의 gradient(미분값)을 0으로 초기화한다.
   - optimizer.zero_grad()
1. 랜덤한 값을 여러번을 거쳐 정답을 찾는다
- 위의 단계를 반복한다.   

In [ ]:
epochs = 2000 # 최적화 작업을 몇번 반복할지
lr = 0.01

for epoch in range(epochs):
    #1. 추론
    pred = linear_model(X_train)
    #2. 오차계산
    loss = mse_loss(pred, y_train)
    #3. 파라미터들에 대한 gradient 계산.
    loss.backward()
    #4. 파라미터 업데이트(최적화)
    weight.data = weight.data - lr * weight.grad # 여러번 반복 한다.
    bias.data = bias.data - lr * bias.grad
    #5. 파라미터 grad 초기화
    weight.grad = None
    bias.grad = None

    if epoch % 100 == 0 or epoch == (epochs-1): # 100번 반복당, 마지막에 loss출력 (로그)
        print(f"[{epoch+1}/{epoch}] - Loss : {loss.item()}")


[1/0] - Loss : 3.022451639175415
[101/100] - Loss : 1.8676906824111938
[201/200] - Loss : 1.1541200876235962
[301/300] - Loss : 0.7131769061088562
[401/400] - Loss : 0.44069790840148926
[501/500] - Loss : 0.2723253667354584
[601/600] - Loss : 0.1682804375886917
[701/700] - Loss : 0.10398700088262558
[801/800] - Loss : 0.06425701081752777
[901/900] - Loss : 0.03970620408654213
[1001/1000] - Loss : 0.024536199867725372
[1101/1100] - Loss : 0.015161720104515553
[1201/1200] - Loss : 0.009369232691824436
[1301/1300] - Loss : 0.0057897078804671764
[1401/1400] - Loss : 0.003577650524675846
[1501/1500] - Loss : 0.0022106769029051065
[1601/1600] - Loss : 0.0013660703552886844
[1701/1700] - Loss : 0.0008442692342214286
[1801/1800] - Loss : 0.0005217598518356681
[1901/1900] - Loss : 0.0003224618558306247
[2000/1999] - Loss : 0.00020027982827741653


In [40]:
weight.data, bias.data

(tensor([[19.9836]]), tensor([0.0373]))

In [42]:
with torch.no_grad():
    p = linear_model(X_train)
    print(p)
linear_model(X_train)

tensor([[20.0209],
        [40.0045],
        [59.9881]])


tensor([[20.0209],
        [40.0045],
        [59.9881]], grad_fn=<AddBackward0>)

In [43]:
time = torch.tensor([[6], [8.2]], dtype=torch.float32)
with torch.no_grad():
    p2 = linear_model(time)
    print(p2)

tensor([[119.9389],
        [163.9028]])


# 다중 입력, 다중 출력
- 다중입력: Feature가 여러개인 경우 (온도, 강수량, 습도) 
- 다중출력: Output 결과가 여러개인 경우 ( 사과생산량, 오렌지생산량)
- <font color='red'>데이터 개수 5, feature 3 (5,3) | feature 3 , output 2 (3,2) | (5,3)@(3,2) 최종 나와야 하는 값 (5,2)</font>

다음 가상 데이터를 이용해 사과와 오렌지 수확량을 예측하는 선형회귀 모델을 정의한다.  
[참조](https://www.kaggle.com/code/aakashns/pytorch-basics-linear-regression-from-scratch)


|온도(F)|강수량(mm)|습도(%)|사과생산량(ton)|오렌지생산량|
|-|-|-|-:|-:|
|73|67|43|56|70|
|91|88|64|81|101|
|87|134|58|119|133|
|102|43|37|22|37|
|69|96|70|103|119|

```
사과수확량  = w11 * 온도 + w12 * 강수량 + w13 * 습도 + b1
오렌지수확량 = w21 * 온도 + w22 * 강수량 + w23 *습도 + b2
```

- `온도`, `강수량`, `습도` 값이 **사과**와, **오렌지 수확량**에 어느정도 영향을 주는지 가중치를 찾는다.
    - 모델은 사과의 수확량, 오렌지의 수확량 **두개의 예측결과를 출력**해야 한다.
    - 사과에 대해 예측하기 위한 weight 3개와 오렌지에 대해 예측하기 위한 weight 3개 이렇게 두 묶음, 총 6개의 weight를 정의하고 학습을 통해 가장 적당한 값을 찾는다.
        - `개별 과일를 예측하기 위한 weight들 @ feature들` 의 계산 결과를  **<font color='red'>Node, Unit, Neuron</font>** 이라고 한다.
        - 두 과일에 대한 Unit들을 묶어서 **Layer** 라고 한다.
- 목적은 우리가 수집한 train 데이터셋을 이용해 **정확한 예측을 위한 weight와 bias 들**을 찾는 것이다.

## Train Dataset
- Train data는 feature(input)와 target(output) 각각 2개의 행렬로 구성한다.
- Feature의 행은 관측치(개별 데이터)를 열을 Feature(특성, 변수)를 표현한다. 이 문제에서는 `온도, 강수량, 습도` 세개의 변수를 가진다.
- Target은 모델이 예측할 대상으로 행은 개별 관측치, 열은 각 항목에 대한 정답으로 구성한다. 이 문제에서 예측할 항목은 `사과수확량, 오렌지 수확량` 2개의 값이다.

In [1]:
#  input: 생산환경 (temp, rainfall, humidity) : (5, 3)
environs = [
    [73, 67, 43], 
    [91, 88, 64], 
    [87, 134, 58], 
    [102, 43, 37], 
    [69, 96, 70]
]

# Targets: 생산량 - (apples, oranges) - (5, 2)
apple_orange_output = [
    [56, 70], 
    [81, 101], 
    [119, 133], 
    [22, 37], 
    [103, 119]
]

In [ ]:
import torch
# Dataset을 torch.Tensor로 생성
X = torch.tensor(environs, dtype=torch.float32) # 고정된 값이기 때문에 requires_grad=True 할 필요가 없다
y = torch.tensor(apple_orange_output, dtype=torch.float32)
X.shape, y.shape

(torch.Size([5, 3]), torch.Size([5, 2]))

In [3]:
X

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

## weight와 bias
- weight: 각 feature들이 생산량에 영향을 주었는지의 가중치로 feature에 곱해줄 값.
    - 사과, 오렌지의 생산량을 구해야 하므로 가중치가 두개가 된다.
    - weight의 shape: `(3, 2)`
- bias는 모든 feature들이 0일때 생산량이 얼마일지를 나타내는 값으로 feature와 weight간의 가중합 결과에 더해줄 값이다.
    - 사과, 오렌지의 생산량을 구하므로 bias가 두개가 된다.
    - bias의 shape: `(2, )`

### Linear Regression model
모델은 weights `w`와 inputs `x`의 내적(dot product)한 값에 bias `b`를 더하는 함수.

$$
\hspace{2.5cm} X \hspace{1.1cm} \cdot \hspace{1.2cm} W \hspace{1.2cm}  + \hspace{1cm} b \hspace{2cm}
$$

$$
\left[ \begin{array}{cc}
73 & 67 & 43 \\
91 & 88 & 64 \\
\vdots & \vdots & \vdots \\
69 & 96 & 70
\end{array} \right]
%
\cdot
%
\left[ \begin{array}{cc}
w_{11} & w_{21} \\
w_{12} & w_{22} \\
w_{13} & w_{23}
\end{array} \right]
%
+
%
\left[ \begin{array}{cc}
b_{1} & b_{2} \\
b_{1} & b_{2} \\
\vdots & \vdots \\
b_{1} & b_{2} \\
\end{array} \right]
$$


<center style="font-size:0.9em">
$w_{11},\,w_{12},\,w_{13}$: 사과 생산량 계산시 각 feature들(생산환경)에 곱할 가중치   <br>
$w_{21},\,w_{22},\,w_{23}$: 오렌지 생산량 계산시 각 feature들(생산환경)에 곱할 가중치    
</center>

<center>
<img src="https://raw.githubusercontent.com/kgmyhGit/image_resource/main/deeplearning/figures/3_unit_layer.png">
</center>

In [4]:
### 모델링
# weight shape : (3: feature개수, 2: output의 개수)
weight = torch.randn(3,2, requires_grad=True)
# bias shape: (2: output의 개수.)
bias = torch.randn(2, requires_grad=True)

def model(X):
    return X @ weight + bias

In [ ]:
y_hat = model(X)
print(y_hat.shape)  # (5: 개수, 2: 과일생산량(사과, 오렌지))
print(y_hat)

torch.Size([5, 2])
tensor([[ -86.4813,   67.1004],
        [-111.2129,  100.8998],
        [-105.9904,  122.6102],
        [-112.0343,   31.3877],
        [ -92.1716,  123.7261]], grad_fn=<AddBackward0>)


In [7]:
y

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [9]:
# Loss 함수
def loss_fn(pred, y):
    """mean squared error"""
    return torch.mean((pred - y)**2)

In [10]:
## 학습 (trainset을 이용해서 weight, bias를 최적화)
epochs = 5000
lr = 0.00001

for epoch in range(epochs):
    # 1. 모델을 이용해서 예측
    pred = model(X)
    # 2. 오차 계산
    loss = loss_fn(pred, y)
    # 3. weight와 bias의 gradient를 계산
    loss.backward()
    # 4. weight와 bias 최적화
    weight.data = weight.data - lr * weight.grad
    bias.data = bias.data - lr * bias.grad
    # 5. grad 초기화
    weight.grad = None
    bias.grad = None

    # 로그 출력 (epoch별 loss 출력)
    ### # 100 epoch 당 1번 씩 , 마지막 epoch
    if epoch % 100 == 0 or epoch == (epochs - 1):
        print(f"[{epoch}/{epochs}] - loss: {loss.item(): 5f}")

[0/5000] - loss:  16409.478516
[100/5000] - loss:  24.605507
[200/5000] - loss:  18.208025
[300/5000] - loss:  14.547537
[400/5000] - loss:  11.972875
[500/5000] - loss:  9.966549
[600/5000] - loss:  8.338482
[700/5000] - loss:  6.997939
[800/5000] - loss:  5.888691
[900/5000] - loss:  4.969220
[1000/5000] - loss:  4.206655
[1100/5000] - loss:  3.574040
[1200/5000] - loss:  3.049241
[1300/5000] - loss:  2.613847
[1400/5000] - loss:  2.252641
[1500/5000] - loss:  1.952974
[1600/5000] - loss:  1.704366
[1700/5000] - loss:  1.498112
[1800/5000] - loss:  1.327006
[1900/5000] - loss:  1.185053
[2000/5000] - loss:  1.067284
[2100/5000] - loss:  0.969560
[2200/5000] - loss:  0.888505
[2300/5000] - loss:  0.821254
[2400/5000] - loss:  0.765465
[2500/5000] - loss:  0.719176
[2600/5000] - loss:  0.680783
[2700/5000] - loss:  0.648922
[2800/5000] - loss:  0.622496
[2900/5000] - loss:  0.600565
[3000/5000] - loss:  0.582375
[3100/5000] - loss:  0.567287
[3200/5000] - loss:  0.554762
[3300/5000] - 

In [12]:
print(weight)
print("="*100)
print(bias)

tensor([[-0.3939, -0.2962],
        [ 0.8496,  0.7925],
        [ 0.6877,  0.9208]], requires_grad=True)
tensor([-0.6847, -0.9157], requires_grad=True)


In [14]:
### 학습된 모델로 추론
with torch.no_grad():
    p = model(X)
    print(p)

tensor([[ 57.0542,  70.1517],
        [ 82.2469, 100.7993],
        [118.7784, 132.9147],
        [ 21.1146,  37.0154],
        [101.8355, 119.1818]])


In [15]:
y

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
new_X = [[63.2, 121.6, 32.1]]
new_X = torch.tensor(new_X, dtype=torch.float32)
with torch.no_grad():
    new_pred = model(new_X)
    print(new_pred)

    print("사과 예측 생산량:", new_pred[0,0].item()) # 첫번째 지역 사과
    print("오렌지 예측 생산량", new_pred[0,1].item()) # 첫번째 지역 오렌지

tensor([[ 99.8073, 106.2888]])
사과 예측 생산량: 99.80733489990234
오렌지 예측 생산량 106.28883361816406


# pytorch built-in(구현된) 모델을 사용해 Linear Regression 구현

In [17]:
inputs = torch.tensor(
    [[73, 67, 43], 
     [91, 88, 64], 
     [87, 134, 58], 
     [102, 43, 37], 
     [69, 96, 70]], dtype=torch.float32)

In [18]:
targets = torch.tensor(
    [[56, 70], 
    [81, 101], 
    [119, 133], 
    [22, 37], 
    [103, 119]], dtype=torch.float32)

## torch.nn.Linear ( 딥러닝은 대부분 nn에 들어있다 )
Pytorch는 torch.nn.Linear 클래스를 통해 Linear Regression 모델을 제공한다.  
torch.nn.Linear에 입력 feature의 개수와 출력 값의 개수를 지정하면 random 값으로 초기화한 weight와 bias들을 생성해 모델을 구성한다.
- `torch.nn.Linear(input feature의 개수 , output 값의 개수)`

## Optimizer와 Loss 함수 정의
- **Optimizer**: 계산된 gradient값을 이용해 파라미터들을 업데이트 하는 함수
- **Loss 함수**: <font color='red'>정답과 모델이 예측한 값사이의 차이(오차)를 계산하는 함수.</font>
  - 모델을 최적화하는 것은 이 함수의 값을 최소화하는 것을 말한다. 
- `torch.optim` <font color='red'>모듈에 다양한 Optimizer 클래스가 구현되있다.</font>
- `torch.nn` 또는 `torch.nn.functional` 모듈에 다양한 Loss 함수가 제공된다. 

In [19]:
inputs.shape, targets.shape

(torch.Size([5, 3]), torch.Size([5, 2]))

In [21]:
# 선형회귀 모델을 정의. torch.nn.Linear 클래스
import torch
import torch.nn as nn

model = nn.Linear(3, 2)  # 3: input feature 개수, 2: output 수 | randn에 들어가는 값과 같음

In [ ]:
# loss 함수
loss_fn = torch.nn.MSELoss()  # 클래스
# loss_fn = torch.nn.functional.mse_loss # 함수 , 위 와 둘중 하나만 사용해도 괜찮으나 .mse_loss는 예전 버전

In [23]:
# optimizer (torch.optim 모듈에 정의): weight.data = weight.data - lr * weight.grad
optimizer = torch.optim.SGD(
    model.parameters(), # 최적화 대상 파라미터들(weight, bias들)을 model에서 조회해서 전달.
    lr = 0.00001,       # Learning Rage
)

In [24]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.2381,  0.3852,  0.2902],
         [ 0.4234, -0.5710, -0.4601]], requires_grad=True),
 Parameter containing:
 tensor([-0.5687,  0.4392], requires_grad=True)]

## Model Train

In [30]:
model(inputs) # callable
class Test:

    def __call__(self, x, y):
        return x + y
t = Test()
t(10,20)
#model

30

In [ ]:
epochs = 5000

for epoch in range(epochs):
    # 추론
    pred = model(inputs)  
    # loss 계산
    loss = loss_fn(pred, targets) # torch.nn.functional.mse_loss(pred, targets) # (모델추정값, 정답)
    # gradient 계산
    loss.backward()
    # 파라미터 업데이트: optimizer.step()
    optimizer.step() # w.data = w.data - lr * w.grad
    # 파라미터 초기화 w.grad=None, b.grad=None
    optimizer.zero_grad()
    # 현재 epoch 학습 결과를 log로 출력
    if epoch % 100 == 0 or epoch == epochs-1:
        print(f"[{epoch+1:04d}/{epochs}] - {loss.item()}")

[0001/5000] - 11465.0732421875
[0101/5000] - 265.5790100097656
[0201/5000] - 93.728515625
[0301/5000] - 42.297080993652344
[0401/5000] - 25.20303726196289
[0501/5000] - 18.19784164428711
[0601/5000] - 14.399932861328125
[0701/5000] - 11.814192771911621
[0801/5000] - 9.827577590942383
[0901/5000] - 8.223872184753418
[1001/5000] - 6.905952453613281
[1101/5000] - 5.8160295486450195
[1201/5000] - 4.9128007888793945
[1301/5000] - 4.163717746734619
[1401/5000] - 3.542344331741333
[1501/5000] - 3.0268685817718506
[1601/5000] - 2.5992231369018555
[1701/5000] - 2.2444252967834473
[1801/5000] - 1.9500815868377686
[1901/5000] - 1.7058912515640259
[2001/5000] - 1.5032882690429688
[2101/5000] - 1.3352075815200806
[2201/5000] - 1.1957783699035645
[2301/5000] - 1.0800997018814087
[2401/5000] - 0.9841251373291016
[2501/5000] - 0.9044992327690125
[2601/5000] - 0.8384512066841125
[2701/5000] - 0.7836438417434692
[2801/5000] - 0.7381768822669983
[2901/5000] - 0.7004597187042236
[3001/5000] - 0.6691692471

In [32]:
# 추론 => gradient 계산을 할 필요가 없다. ==> grad_fn을 만들 필요가 없다. 그래서 torch.no_grad() 블록에서 추론 작업을 실행한다.
with torch.no_grad():
    pred = model(inputs)

In [33]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [34]:
pred

tensor([[ 57.0718,  70.3898],
        [ 82.2519, 100.5657],
        [118.7391, 133.0676],
        [ 21.1021,  37.0399],
        [101.8746, 119.0287]])

In [35]:
loss_fn(pred, targets)

tensor(0.5204)

In [36]:
# 학습 로직을 함수 구현
def train(inputs, targets, epochs, model, loss_fn, optimizer): # fit 같은 역할

    for epoch in range(epochs):
        # 추론
        pred = model(inputs)
        # loss 계산
        loss = loss_fn(pred, targets) # torch.nn.functional.mse_loss(pred, targets) # (모델추정값, 정답)
        # gradient 계산
        loss.backward()
        # 파라미터 업데이트: optimizer.step()
        optimizer.step()
        # 파라미터 초기화 w.grad=None, b.grad=None
        optimizer.zero_grad()
        # 현재 epoch 학습 결과를 log로 출력
        if epoch % 100 == 0 or epoch == epochs-1:
            print(f"[{epoch+1:04d}/{epochs}] - {loss.item()}")

In [37]:
model = nn.Linear(3, 2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)

In [ ]:
train(inputs, targets, 5000, model, nn.functional.mse_loss, optimizer) # 함수화

[0001/5000] - 2461.2001953125
[0101/5000] - 1.353010892868042
[0201/5000] - 0.6352109909057617
[0301/5000] - 0.5253031253814697
[0401/5000] - 0.5084631443023682
[0501/5000] - 0.5058735609054565
[0601/5000] - 0.5054775476455688
[0701/5000] - 0.5054119229316711
[0801/5000] - 0.5053993463516235
[0901/5000] - 0.5053936243057251
[1001/5000] - 0.5053900480270386
[1101/5000] - 0.5053838491439819
[1201/5000] - 0.5053848028182983
[1301/5000] - 0.5053814053535461
[1401/5000] - 0.5053750872612
[1501/5000] - 0.5053723454475403
[1601/5000] - 0.5053688287734985
[1701/5000] - 0.5053662657737732
[1801/5000] - 0.5053588151931763
[1901/5000] - 0.50535649061203
[2001/5000] - 0.5053540468215942
[2101/5000] - 0.5053495764732361
[2201/5000] - 0.5053471922874451
[2301/5000] - 0.5053449869155884
[2401/5000] - 0.5053409337997437
[2501/5000] - 0.5053365230560303
[2601/5000] - 0.5053321123123169
[2701/5000] - 0.5053308010101318
[2801/5000] - 0.5053262114524841
[2901/5000] - 0.5053247809410095
[3001/5000] - 0.505

In [42]:
# model(inputs)

with torch.no_grad():
    p = model(inputs)
    pred = p
    pred